FROM centos:7
RUN yum install httpd -y 
#CMD ['systemctl','start','httpd']
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html /var/www/html/index.html
RUN  echo ProxyPass /student http://172.17.0.3:8080/student >> /etc/httpd/conf/httpd.conf
RUN echo ProxyPassReverse /student http://172.17.0.3:8080/student >> /etc/httpd/conf/httpd.conf
EXPOSE 80
CMD ["httpd","-DFOREGROUND"]